apiVersion: v1
kind: Secret
metadata:
  name: db-password-secret
  namespace: crud-app
type: Opaque
data:
  password: QXAwMHJQYSQkdzByZCE=


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: crud-app
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: password
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-volume
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pvc



---


apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: crud-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: crud-app
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: final_assignment-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: db_username
              value: postgres
            - name: db_name
              value: postgres
            - name: db_address
              value: postgres
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: crud-app
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: crud-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi



